import { Suspense } from "react";
import { redirect } from "next/navigation";
import { getPrincipal } from "@/lib/auth";
import { logoutAction } from "@/app/login/actions";
import { Nav } from "@/components/Nav";

export default async function AppLayout({ children }: { children: React.ReactNode }) {
  const principal = await getPrincipal();
  if (!principal) redirect("/login");

  return (
    <div className="min-h-screen">
      <header
        className="sticky top-0 z-10 border-b backdrop-blur"
        style={{ background: "color-mix(in srgb, var(--page) 88%, transparent)" }}
      >
        <div className="mx-auto flex max-w-[1400px] flex-wrap items-center gap-x-6 gap-y-2 px-6 py-3">
          <div className="flex items-baseline gap-2">
            <span className="text-sm font-semibold tracking-tight">ROAS</span>
            <span className="text-xs" style={{ color: "var(--text-muted)" }}>
              {principal.brand.name}
            </span>
          </div>

          <Suspense fallback={<div className="h-8" />}>
            <Nav />
          </Suspense>

          <form action={logoutAction} className="ml-auto">
            <button
              type="submit"
              className="text-xs hover:underline"
              style={{ color: "var(--text-secondary)" }}
            >
              Sign out
            </button>
          </form>
        </div>
      </header>

      <main className="mx-auto max-w-[1400px] px-6 py-6">{children}</main>

      <footer
        className="mx-auto max-w-[1400px] px-6 pb-10 pt-4 text-[11px]"
        style={{ color: "var(--text-muted)" }}
      >
        Figures shown are generated by the local sandbox connectors unless a platform account
        is switched to live mode in Settings. Money is stored and computed in paise; ROAS and
        CAC use the definitions documented in <code>docs/metrics.md</code>.
      </footer>
    </div>
  );
}
